const keywords = [
  { words: ['tişört', 'tshirt', 't-shirt'], emoji: '👕' },
  { words: ['elbise', 'fistan', 'abiye'], emoji: '👗' },
  { words: ['pantolon', 'kot', 'jean'], emoji: '👖' },
  { words: ['şort', 'bermuda'], emoji: '🩳' },
  { words: ['kazak', 'sweatshirt', 'hoodie', 'hırka'], emoji: '🧥' },
  { words: ['mont', 'ceket'], emoji: '🧥' },
  { words: ['gömlek'], emoji: '👔' },
  { words: ['ayakkabı', 'bot', 'sandalet', 'terlik', 'sneaker'], emoji: '👟' },
  { words: ['çorap'], emoji: '🧦' },
  { words: ['şapka', 'bere', 'kep'], emoji: '🧢' },
  { words: ['kıyafet', 'giyim', 'giysi'], emoji: '👗' },
  { words: ['aksesuar'], emoji: '💍' },
  { words: ['takı', 'kolye', 'bileklik', 'yüzük', 'küpe'], emoji: '💍' },
  { words: ['çanta'], emoji: '👜' },
  { words: ['gözlük', 'güneş'], emoji: '🕶️' },
  { words: ['kemer'], emoji: '🎗️' },
  { words: ['yiyecek', 'yemek', 'gıda', 'atıştırmalık'], emoji: '🍽️' },
  { words: ['içecek', 'su', 'meyve suyu', 'meşrubat'], emoji: '🥤' },
  { words: ['kahve', 'espresso', 'latte'], emoji: '☕' },
  { words: ['çay'], emoji: '🍵' },
  { words: ['pasta', 'kek', 'tatlı'], emoji: '🎂' },
  { words: ['kurabiye', 'bisküvi'], emoji: '🍪' },
  { words: ['börek', 'poğaça', 'simit', 'ekmek'], emoji: '🥐' },
  { words: ['sandviç', 'tost', 'dürüm'], emoji: '🥪' },
  { words: ['pizza'], emoji: '🍕' },
  { words: ['meyve'], emoji: '🍎' },
  { words: ['sebze'], emoji: '🥦' },
  { words: ['çikolata', 'şeker', 'şekerleme', 'lokum'], emoji: '🍫' },
  { words: ['kitap', 'roman', 'hikaye', 'şiir'], emoji: '📚' },
  { words: ['kırtasiye', 'defter', 'kalem', 'boya'], emoji: '✏️' },
  { words: ['dergi', 'gazete'], emoji: '📰' },
  { words: ['oyuncak', 'figür', 'koleksiyon'], emoji: '🧸' },
  { words: ['lego', 'yapboz', 'puzzle', 'bulmaca'], emoji: '🧩' },
  { words: ['kutu oyun', 'board game'], emoji: '🎲' },
  { words: ['elektronik'], emoji: '📱' },
  { words: ['telefon', 'cep'], emoji: '📱' },
  { words: ['kulaklık'], emoji: '🎧' },
  { words: ['bilgisayar', 'laptop', 'tablet'], emoji: '💻' },
  { words: ['kablo', 'adaptör', 'şarj'], emoji: '🔌' },
  { words: ['ev eşyası', 'mutfak'], emoji: '🏠' },
  { words: ['dekorasyon', 'dekor', 'süsleme'], emoji: '🖼️' },
  { words: ['çiçek', 'bitki', 'saksı', 'buket'], emoji: '🌸' },
  { words: ['mum', 'mumluk'], emoji: '🕯️' },
  { words: ['spor', 'fitness'], emoji: '⚽' },
  { words: ['futbol'], emoji: '⚽' },
  { words: ['basketbol'], emoji: '🏀' },
  { words: ['sanat', 'resim', 'tablo', 'suluboya'], emoji: '🎨' },
  { words: ['el işi', 'el yapımı', 'handmade', 'örgü', 'nakış'], emoji: '🧶' },
  { words: ['seramik', 'çömlek'], emoji: '🏺' },
  { words: ['bardak', 'kupa', 'fincan'], emoji: '🥤' },
  { words: ['tabak', 'kase'], emoji: '🍽️' },
  { words: ['müzik', 'enstrüman', 'gitar', 'piyano'], emoji: '🎵' },
  { words: ['bebek ürün', 'bebek kıyafet'], emoji: '👶' },
]

export function getEmoji(text) {
  if (!text || text.trim() === '') return '🏷️'
  const lower = text.toLowerCase().trim()
  for (const { words, emoji } of keywords) {
    if (words.some(w => lower.includes(w))) return emoji
  }
  return '🏷️'
}
